create table authorities (user_id binary not null, authorities varchar(255));
create table course (id bigint generated by default as identity, description varchar(255), primary key (id));
create table course_rating (id bigint generated by default as identity, rating double not null, course_id bigint, user_id binary, primary key (id));
create table users (id binary not null, password varchar(255), username varchar(255), confirm_code varchar(255), full_name varchar(255), gender varchar(255), image_url varchar(255), enabled boolean, locale varchar(255), old integer not null, provider varchar(255), primary key (id));
alter table authorities add constraint authorities_user_fk foreign key (user_id) references users;
alter table course_rating add constraint course_rating_fk foreign key (course_id) references course;
alter table course_rating add constraint user_rating_fk foreign key (user_id) references users