create table authorities (user_id uuid not null, authorities varchar(255));
create table course (id int8 generated by default as identity, description varchar(255), primary key (id));
create table course_rating (id int8 generated by default as identity, rating float8 not null, course_id int8, user_id uuid, primary key (id));
create table users (id uuid not null, password varchar(255), username varchar(255), confirm_code varchar(255), full_name varchar(255), gender varchar(255), image_url varchar(255), enabled boolean, locale varchar(255), old int4 not null, provider varchar(255), primary key (id));
alter table if exists authorities add constraint authorities_user_fk foreign key (user_id) references users;
alter table if exists course_rating add constraint course_rating_fk foreign key (course_id) references course;
alter table if exists course_rating add constraint user_rating_fk foreign key (user_id) references users